squash: false
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:19.0.0
  amd64: ghcr.io/hassio-addons/base/amd64:19.0.0
  armhf: ghcr.io/hassio-addons/base/armhf:18.2.1
  armv7: ghcr.io/hassio-addons/base/armv7:18.2.1
  i386: ghcr.io/hassio-addons/base/i386:18.2.1
