squash: false
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:16.0.1
  amd64: ghcr.io/hassio-addons/base/amd64:16.0.1
  armhf: ghcr.io/hassio-addons/base/armhf:16.0.1
  armv7: ghcr.io/hassio-addons/base/armv7:16.0.1
  i386: ghcr.io/hassio-addons/base/i386:16.0.1
