squash: false
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:15.0.5
  amd64: ghcr.io/hassio-addons/base/amd64:15.0.5
  armhf: ghcr.io/hassio-addons/base/armhf:15.0.5
  armv7: ghcr.io/hassio-addons/base/armv7:15.0.5
  i386: ghcr.io/hassio-addons/base/i386:15.0.5
