squash: false
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:18.1.4
  amd64: ghcr.io/hassio-addons/base/amd64:18.1.4
  armhf: ghcr.io/hassio-addons/base/armhf:18.1.4
  armv7: ghcr.io/hassio-addons/base/armv7:18.1.4
  i386: ghcr.io/hassio-addons/base/i386:18.1.4
