squash: false
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:17.2.0
  amd64: ghcr.io/hassio-addons/base/amd64:17.2.0
  armhf: ghcr.io/hassio-addons/base/armhf:17.2.0
  armv7: ghcr.io/hassio-addons/base/armv7:17.2.0
  i386: ghcr.io/hassio-addons/base/i386:17.2.0
